package ru.unitarius.integration.service.cards;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.sun.xml.internal.ws.developer.SchemaValidation;

/**
 * This class was generated by Apache CXF 3.1.4.redhat-1
 * 2017-07-12T14:09:48.688+03:00
 * Generated source version: 3.1.4.redhat-1
 * 
 */
//
//@org.jboss.ws.annotation.SchemaValidation(enabled = true)
@SchemaValidation
@WebService(targetNamespace = "http://unitarius.ru/integration/service/cards", name = "PortTypeCardsService")
@XmlSeeAlso({ru.unitarius.integration.schema.cards.ObjectFactory.class, ru.unitarius.integration.schema.common.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PortTypeCardsService {

    @WebMethod(action = "http://unitarius.ru/integration/service/cards/getCardLists")
    @WebResult(name = "CardListRes", targetNamespace = "http://unitarius.ru/integration/schema/cards", partName = "parameters")
    public ru.unitarius.integration.schema.cards.CardListResType getCardList(
        @WebParam(partName = "parameters", name = "CardListReq", targetNamespace = "http://unitarius.ru/integration/schema/cards")
        ru.unitarius.integration.schema.cards.CardListReqType parameters
    ) throws MsgFault;

    @WebMethod(action = "http://unitarius.ru/integration/service/cards/getCardStatusHistory")
    @WebResult(name = "CardStatusHistoryRes", targetNamespace = "http://unitarius.ru/integration/schema/cards", partName = "parameters")
    public ru.unitarius.integration.schema.cards.CardStatusHistoryResType getCardStatusHistory(
        @WebParam(partName = "parameters", name = "CardStatusHistoryReq", targetNamespace = "http://unitarius.ru/integration/schema/cards")
        ru.unitarius.integration.schema.cards.CardStatusHistoryReqType parameters
    ) throws MsgFault;

    @WebMethod(action = "http://unitarius.ru/integration/service/cards/getCardLimits")
    @WebResult(name = "CardLimitsRes", targetNamespace = "http://unitarius.ru/integration/schema/cards", partName = "parameters")
    public ru.unitarius.integration.schema.cards.CardLimitsResType getCardLimits(
        @WebParam(partName = "parameters", name = "CardLimitsReq", targetNamespace = "http://unitarius.ru/integration/schema/cards")
        ru.unitarius.integration.schema.cards.CardLimitsReqType parameters
    ) throws MsgFault;

    @WebMethod(action = "http://unitarius.ru/integration/service/cards/isCorrectCodeword")
    @WebResult(name = "CheckCodewordRes", targetNamespace = "http://unitarius.ru/integration/schema/cards", partName = "parameters")
    public ru.unitarius.integration.schema.cards.CheckCodewordResType isCorrectCodeword(
        @WebParam(partName = "parameters", name = "CheckCodewordReq", targetNamespace = "http://unitarius.ru/integration/schema/cards")
        ru.unitarius.integration.schema.cards.CheckCodewordReqType parameters
    ) throws MsgFault;

    @WebMethod(action = "http://unitarius.ru/integration/service/cards/getCardPaymentSchedule")
    @WebResult(name = "CardPaymentScheduleRes", targetNamespace = "http://unitarius.ru/integration/schema/cards", partName = "parameters")
    public ru.unitarius.integration.schema.cards.CardPaymentScheduleResType getCardPaymentSchedule(
        @WebParam(partName = "parameters", name = "CardPaymentScheduleReq", targetNamespace = "http://unitarius.ru/integration/schema/cards")
        ru.unitarius.integration.schema.cards.CardPaymentScheduleReqType parameters
    ) throws MsgFault;

    @WebMethod(action = "http://unitarius.ru/integration/service/cards/getCardStatus")
    @WebResult(name = "CardStatusRes", targetNamespace = "http://unitarius.ru/integration/schema/cards", partName = "parameters")
    public ru.unitarius.integration.schema.cards.CardStatusResType getCardStatus(
        @WebParam(partName = "parameters", name = "CardStatusReq", targetNamespace = "http://unitarius.ru/integration/schema/cards")
        ru.unitarius.integration.schema.cards.CardStatusReqType parameters
    ) throws MsgFault;

    @WebMethod(action = "http://unitarius.ru/integration/service/cards/getCardStatement")
    @WebResult(name = "StatementRes", targetNamespace = "http://unitarius.ru/integration/schema/cards", partName = "parameters")
    public ru.unitarius.integration.schema.cards.StatementResType getCardStatement(
        @WebParam(partName = "parameters", name = "StatementReq", targetNamespace = "http://unitarius.ru/integration/schema/cards")
        ru.unitarius.integration.schema.cards.StatementReqType parameters
    ) throws MsgFault;

    @WebMethod(action = "http://unitarius.ru/integration/service/cards/getCardInfo")
    @WebResult(name = "CardInfoRes", targetNamespace = "http://unitarius.ru/integration/schema/cards", partName = "parameters")
    public ru.unitarius.integration.schema.cards.CardInfoResType getCardInfo(
        @WebParam(partName = "parameters", name = "CardInfoReq", targetNamespace = "http://unitarius.ru/integration/schema/cards")
        ru.unitarius.integration.schema.cards.CardInfoReqType parameters
    ) throws MsgFault;

    @WebMethod(action = "http://unitarius.ru/integration/service/cards/getCardPhoneNumber")
    @WebResult(name = "CardPhoneNumberRes", targetNamespace = "http://unitarius.ru/integration/schema/cards", partName = "parameters")
    public ru.unitarius.integration.schema.cards.CardPhoneNumberResType getCardPhoneNumber(
        @WebParam(partName = "parameters", name = "CardPhoneNumberReq", targetNamespace = "http://unitarius.ru/integration/schema/cards")
        ru.unitarius.integration.schema.cards.CardPhoneNumberReqType parameters
    ) throws MsgFault;
}
