package org.wso2.ws.dataservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4.redhat-1
 * 2017-10-05T16:08:29.424+03:00
 * Generated source version: 3.1.4.redhat-1
 * 
 */
@WebService(targetNamespace = "http://ws.wso2.org/dataservice", name = "CTX_DBO_NEWPortType")
@XmlSeeAlso({avlbal.ObjectFactory.class, ObjectFactory.class, currcode.ObjectFactory.class, blkamt.ObjectFactory.class, actioncode.ObjectFactory.class, pan.ObjectFactory.class})
public interface CTXDBONEWPortType {

    @WebMethod(action = "urn:getCardSettlement")
    @Action(input = "urn:getCardSettlement", output = "urn:getCardSettlementResponse", fault = {@FaultAction(className = DataServiceFault_Exception.class, value = "urn:getCardSettlementDataServiceFault")})
    @RequestWrapper(localName = "getCardSettlement", targetNamespace = "http://ws.wso2.org/dataservice", className = "org.wso2.ws.dataservice.GetCardSettlement")
    @ResponseWrapper(localName = "CardSettlements", targetNamespace = "http://ws.wso2.org/dataservice", className = "org.wso2.ws.dataservice.CardSettlements")
    @WebResult(name = "CardSettlement", targetNamespace = "http://ws.wso2.org/dataservice")
    public java.util.List<org.wso2.ws.dataservice.CardSettlement> getCardSettlement(
        @WebParam(name = "pan", targetNamespace = "http://ws.wso2.org/dataservice")
        java.lang.String pan,
        @WebParam(name = "startdate", targetNamespace = "http://ws.wso2.org/dataservice")
        java.lang.String startdate,
        @WebParam(name = "enddate", targetNamespace = "http://ws.wso2.org/dataservice")
        java.lang.String enddate
    ) throws DataServiceFault_Exception;

    @WebMethod(action = "urn:getBalance")
    @Action(input = "urn:getBalance", output = "urn:getBalanceResponse", fault = {@FaultAction(className = DataServiceFault_Exception.class, value = "urn:getBalanceDataServiceFault")})
    @RequestWrapper(localName = "getBalance", targetNamespace = "http://ws.wso2.org/dataservice", className = "org.wso2.ws.dataservice.GetBalance")
    @ResponseWrapper(localName = "getBalanceResponse", targetNamespace = "http://ws.wso2.org/dataservice", className = "org.wso2.ws.dataservice.GetBalanceResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.wso2.org/dataservice")
    public java.util.List<org.wso2.ws.dataservice.Return> getBalance(
        @WebParam(name = "pan", targetNamespace = "http://ws.wso2.org/dataservice")
        java.lang.String pan,
        @WebParam(name = "instcode", targetNamespace = "http://ws.wso2.org/dataservice")
        java.lang.String instcode
    ) throws DataServiceFault_Exception;

    @WebMethod(action = "urn:getCurrencyRate")
    @Action(input = "urn:getCurrencyRate", output = "urn:getCurrencyRateResponse", fault = {@FaultAction(className = DataServiceFault_Exception.class, value = "urn:getCurrencyRateDataServiceFault")})
    @RequestWrapper(localName = "getCurrencyRate", targetNamespace = "http://ws.wso2.org/dataservice", className = "org.wso2.ws.dataservice.GetCurrencyRate")
    @ResponseWrapper(localName = "getCurrencyRateResponse", targetNamespace = "http://ws.wso2.org/dataservice", className = "org.wso2.ws.dataservice.GetCurrencyRateResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.wso2.org/dataservice")
    public java.util.List<org.wso2.ws.dataservice.Return2> getCurrencyRate(
        @WebParam(name = "basecurcode", targetNamespace = "http://ws.wso2.org/dataservice")
        java.lang.String basecurcode,
        @WebParam(name = "curcode", targetNamespace = "http://ws.wso2.org/dataservice")
        java.lang.String curcode
    ) throws DataServiceFault_Exception;

    @WebMethod(action = "urn:getRRN")
    @Action(input = "urn:getRRN", output = "urn:getRRNResponse", fault = {@FaultAction(className = DataServiceFault_Exception.class, value = "urn:getRRNDataServiceFault")})
    @RequestWrapper(localName = "getRRN", targetNamespace = "http://ws.wso2.org/dataservice", className = "org.wso2.ws.dataservice.GetRRN")
    @ResponseWrapper(localName = "Entries", targetNamespace = "http://ws.wso2.org/dataservice", className = "org.wso2.ws.dataservice.Entries")
    @WebResult(name = "Entry", targetNamespace = "http://ws.wso2.org/dataservice")
    public java.util.List<org.wso2.ws.dataservice.Entry> getRRN(
        @WebParam(name = "tlogid", targetNamespace = "http://ws.wso2.org/dataservice")
        java.lang.String tlogid
    ) throws DataServiceFault_Exception;
}
