package org.wso2.ws.dataservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.4.redhat-1
 * 2017-10-05T16:08:29.438+03:00
 * Generated source version: 3.1.4.redhat-1
 * 
 */
@WebServiceClient(name = "CTX_DBO_NEW", 
                  wsdlLocation = "http://192.168.77.109:9763/services/CTX_DBO_NEW?wsdl",
                  targetNamespace = "http://ws.wso2.org/dataservice") 
public class CTXDBONEW extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.wso2.org/dataservice", "CTX_DBO_NEW");
    public final static QName SecureSOAP11Endpoint = new QName("http://ws.wso2.org/dataservice", "SecureSOAP11Endpoint");
    public final static QName SecureHTTPEndpoint = new QName("http://ws.wso2.org/dataservice", "SecureHTTPEndpoint");
    public final static QName SOAP11Endpoint = new QName("http://ws.wso2.org/dataservice", "SOAP11Endpoint");
    public final static QName SecureSOAP12Endpoint = new QName("http://ws.wso2.org/dataservice", "SecureSOAP12Endpoint");
    public final static QName HTTPEndpoint = new QName("http://ws.wso2.org/dataservice", "HTTPEndpoint");
    public final static QName SOAP12Endpoint = new QName("http://ws.wso2.org/dataservice", "SOAP12Endpoint");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.77.109:9763/services/CTX_DBO_NEW?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CTXDBONEW.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.77.109:9763/services/CTX_DBO_NEW?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CTXDBONEW(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CTXDBONEW(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CTXDBONEW() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public CTXDBONEW(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CTXDBONEW(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CTXDBONEW(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns CTXDBONEWPortType
     */
    @WebEndpoint(name = "SecureSOAP11Endpoint")
    public CTXDBONEWPortType getSecureSOAP11Endpoint() {
        return super.getPort(SecureSOAP11Endpoint, CTXDBONEWPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CTXDBONEWPortType
     */
    @WebEndpoint(name = "SecureSOAP11Endpoint")
    public CTXDBONEWPortType getSecureSOAP11Endpoint(WebServiceFeature... features) {
        return super.getPort(SecureSOAP11Endpoint, CTXDBONEWPortType.class, features);
    }


    /**
     *
     * @return
     *     returns CTXDBONEWPortType
     */
    @WebEndpoint(name = "SecureHTTPEndpoint")
    public CTXDBONEWPortType getSecureHTTPEndpoint() {
        return super.getPort(SecureHTTPEndpoint, CTXDBONEWPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CTXDBONEWPortType
     */
    @WebEndpoint(name = "SecureHTTPEndpoint")
    public CTXDBONEWPortType getSecureHTTPEndpoint(WebServiceFeature... features) {
        return super.getPort(SecureHTTPEndpoint, CTXDBONEWPortType.class, features);
    }


    /**
     *
     * @return
     *     returns CTXDBONEWPortType
     */
    @WebEndpoint(name = "SOAP11Endpoint")
    public CTXDBONEWPortType getSOAP11Endpoint() {
        return super.getPort(SOAP11Endpoint, CTXDBONEWPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CTXDBONEWPortType
     */
    @WebEndpoint(name = "SOAP11Endpoint")
    public CTXDBONEWPortType getSOAP11Endpoint(WebServiceFeature... features) {
        return super.getPort(SOAP11Endpoint, CTXDBONEWPortType.class, features);
    }


    /**
     *
     * @return
     *     returns CTXDBONEWPortType
     */
    @WebEndpoint(name = "SecureSOAP12Endpoint")
    public CTXDBONEWPortType getSecureSOAP12Endpoint() {
        return super.getPort(SecureSOAP12Endpoint, CTXDBONEWPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CTXDBONEWPortType
     */
    @WebEndpoint(name = "SecureSOAP12Endpoint")
    public CTXDBONEWPortType getSecureSOAP12Endpoint(WebServiceFeature... features) {
        return super.getPort(SecureSOAP12Endpoint, CTXDBONEWPortType.class, features);
    }


    /**
     *
     * @return
     *     returns CTXDBONEWPortType
     */
    @WebEndpoint(name = "HTTPEndpoint")
    public CTXDBONEWPortType getHTTPEndpoint() {
        return super.getPort(HTTPEndpoint, CTXDBONEWPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CTXDBONEWPortType
     */
    @WebEndpoint(name = "HTTPEndpoint")
    public CTXDBONEWPortType getHTTPEndpoint(WebServiceFeature... features) {
        return super.getPort(HTTPEndpoint, CTXDBONEWPortType.class, features);
    }


    /**
     *
     * @return
     *     returns CTXDBONEWPortType
     */
    @WebEndpoint(name = "SOAP12Endpoint")
    public CTXDBONEWPortType getSOAP12Endpoint() {
        return super.getPort(SOAP12Endpoint, CTXDBONEWPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CTXDBONEWPortType
     */
    @WebEndpoint(name = "SOAP12Endpoint")
    public CTXDBONEWPortType getSOAP12Endpoint(WebServiceFeature... features) {
        return super.getPort(SOAP12Endpoint, CTXDBONEWPortType.class, features);
    }

}
