package payment;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import ru.bpc.apigate.ServiceLevelException;
import ru.bpc.apigate.SvfeProcessingException;

/**
 * This class was generated by Apache CXF 3.1.4.redhat-1
 * 2016-12-09T13:24:01.961+03:00
 * Generated source version: 3.1.4.redhat-1
 * 
 */
@WebService(targetNamespace = "http://service.transaction.cortexws.d8.lv", name = "PaymentPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface PaymentPortType {

    @WebMethod(action = "urn:reversePayment")
    @Action(input = "urn:reversePayment", output = "urn:reversePaymentResponse")
    @RequestWrapper(localName = "reversePayment", targetNamespace = "http://service.transaction.cortexws.d8.lv", className = "payment.ReversePayment")
    @ResponseWrapper(localName = "reversePaymentResponse", targetNamespace = "http://service.transaction.cortexws.d8.lv", className = "payment.ReversePaymentResponse")
    @WebResult(name = "return", targetNamespace = "http://service.transaction.cortexws.d8.lv")
    public payment.ReversePaymentRspsInfo reversePayment(
        @WebParam(name = "param0", targetNamespace = "http://service.transaction.cortexws.d8.lv")
        payment.ReversePaymentReqstInfo param0
    );

    @WebMethod(action = "urn:makeCRD2CRD")
    @Action(input = "urn:makeCRD2CRD", output = "urn:makeCRD2CRDResponse")
    @RequestWrapper(localName = "makeCRD2CRD", targetNamespace = "http://service.transaction.cortexws.d8.lv", className = "payment.MakeCRD2CRD")
    @ResponseWrapper(localName = "makeCRD2CRDResponse", targetNamespace = "http://service.transaction.cortexws.d8.lv", className = "payment.MakeCRD2CRDResponse")
    @WebResult(name = "return", targetNamespace = "http://service.transaction.cortexws.d8.lv")
    public payment.CRD2CRDPaymentRspsInfo makeCRD2CRD(
        @WebParam(name = "param0", targetNamespace = "http://service.transaction.cortexws.d8.lv")
        payment.CRD2CRDPaymentReqstInfo param0
    );

    @WebMethod(action = "urn:makePayment")
    @Action(input = "urn:makePayment", output = "urn:makePaymentResponse")
    @RequestWrapper(localName = "makePayment", targetNamespace = "http://service.transaction.cortexws.d8.lv", className = "payment.MakePayment")
    @ResponseWrapper(localName = "makePaymentResponse", targetNamespace = "http://service.transaction.cortexws.d8.lv", className = "payment.MakePaymentResponse")
    @WebResult(name = "return", targetNamespace = "http://service.transaction.cortexws.d8.lv")
    public payment.MakePaymentRspsInfo makePayment(
        @WebParam(name = "param0", targetNamespace = "http://service.transaction.cortexws.d8.lv")
        payment.MakePaymentReqstInfo param0
    );

    @WebMethod(action = "http://www.bpc.ru/apigate/creditCard")
    @WebResult(name = "creditCardResponse", targetNamespace = "http://www.bpc.ru/apigate/command/creditCard/", partName = "parameters")
    public ru.bpc.apigate.general.FinancialTransactionResponseType creditCard(
        @WebParam(partName = "parameters", name = "creditCardRequest", targetNamespace = "http://www.bpc.ru/apigate/command/creditCard/")
        ru.bpc.apigate.command.creditcard.CreditCardRequestType parameters
    ) throws SvfeProcessingException, ServiceLevelException;
    
    @WebMethod(action = "http://www.bpc.ru/apigate/debitCard")
    @WebResult(name = "debitCardResponse", targetNamespace = "http://www.bpc.ru/apigate/command/debitCard/", partName = "parameters")
    public ru.bpc.apigate.general.FinancialTransactionResponseType debitCard(
        @WebParam(partName = "parameters", name = "debitCardRequest", targetNamespace = "http://www.bpc.ru/apigate/command/debitCard/")
        ru.bpc.apigate.command.debitcard.DebitCardRequestType parameters
    ) throws SvfeProcessingException, ServiceLevelException;
    
    
}
