package currency;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4.redhat-1
 * 2016-12-08T13:00:45.835+03:00
 * Generated source version: 3.1.4.redhat-1
 * 
 */
@WebService(targetNamespace = "http://service.currency.cortexws.d8.lv", name = "CurrencyPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface CurrencyPortType {

    @WebMethod(action = "urn:getCurrencyRate")
    @Action(input = "urn:getCurrencyRate", output = "urn:getCurrencyRateResponse")
    @RequestWrapper(localName = "getCurrencyRate", targetNamespace = "http://service.currency.cortexws.d8.lv", className = "currency.GetCurrencyRate")
    @ResponseWrapper(localName = "getCurrencyRateResponse", targetNamespace = "http://service.currency.cortexws.d8.lv", className = "currency.GetCurrencyRateResponse")
    @WebResult(name = "return", targetNamespace = "http://service.currency.cortexws.d8.lv")
    public currency.GetGetCurrencyRateRspsInfo getCurrencyRate(
        @WebParam(name = "param0", targetNamespace = "http://service.currency.cortexws.d8.lv")
        currency.GetGetCurrencyRateRqstInfo param0
    );

}
