package lv.d8.cortexws.currency.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4.redhat-1
 * 2016-12-08T13:02:17.723+03:00
 * Generated source version: 3.1.4.redhat-1
 * 
 */
@WebService(targetNamespace = "http://service.currency.cortexws.d8.lv", name = "CurrencyPortType")
@XmlSeeAlso({lv.d8.cortexws.currency.valueobj.xsd.ObjectFactory.class, ObjectFactory.class, lv.d8.cortexws.common.valueobj.xsd.ObjectFactory.class, lv.d8.ws.valueobj.xsd.ObjectFactory.class})
public interface CurrencyPortType {

    @WebMethod(action = "urn:getCurrencyAlpha")
    @Action(input = "urn:getCurrencyAlpha", output = "urn:getCurrencyAlphaResponse")
    @RequestWrapper(localName = "getCurrencyAlpha", targetNamespace = "http://service.currency.cortexws.d8.lv", className = "lv.d8.cortexws.currency.service.GetCurrencyAlpha")
    @ResponseWrapper(localName = "getCurrencyAlphaResponse", targetNamespace = "http://service.currency.cortexws.d8.lv", className = "lv.d8.cortexws.currency.service.GetCurrencyAlphaResponse")
    @WebResult(name = "return", targetNamespace = "http://service.currency.cortexws.d8.lv")
    public lv.d8.cortexws.currency.valueobj.xsd.GetGetCurrencyAlphaRspsInfo getCurrencyAlpha(
        @WebParam(name = "param0", targetNamespace = "http://service.currency.cortexws.d8.lv")
        lv.d8.cortexws.currency.valueobj.xsd.GetGetCurrencyAlphaRqstInfo param0
    );

    @WebMethod(action = "urn:getCurrencies")
    @Action(input = "urn:getCurrencies", output = "urn:getCurrenciesResponse")
    @RequestWrapper(localName = "getCurrencies", targetNamespace = "http://service.currency.cortexws.d8.lv", className = "lv.d8.cortexws.currency.service.GetCurrencies")
    @ResponseWrapper(localName = "getCurrenciesResponse", targetNamespace = "http://service.currency.cortexws.d8.lv", className = "lv.d8.cortexws.currency.service.GetCurrenciesResponse")
    @WebResult(name = "return", targetNamespace = "http://service.currency.cortexws.d8.lv")
    public lv.d8.cortexws.currency.valueobj.xsd.GetCurrenciesRspsInfo getCurrencies(
        @WebParam(name = "param0", targetNamespace = "http://service.currency.cortexws.d8.lv")
        lv.d8.cortexws.currency.valueobj.xsd.GetCurrenciesRqstInfo param0
    );

    @WebMethod(action = "urn:getCurrencyNum")
    @Action(input = "urn:getCurrencyNum", output = "urn:getCurrencyNumResponse")
    @RequestWrapper(localName = "getCurrencyNum", targetNamespace = "http://service.currency.cortexws.d8.lv", className = "lv.d8.cortexws.currency.service.GetCurrencyNum")
    @ResponseWrapper(localName = "getCurrencyNumResponse", targetNamespace = "http://service.currency.cortexws.d8.lv", className = "lv.d8.cortexws.currency.service.GetCurrencyNumResponse")
    @WebResult(name = "return", targetNamespace = "http://service.currency.cortexws.d8.lv")
    public lv.d8.cortexws.currency.valueobj.xsd.GetGetCurrencyNumRspsInfo getCurrencyNum(
        @WebParam(name = "param0", targetNamespace = "http://service.currency.cortexws.d8.lv")
        lv.d8.cortexws.currency.valueobj.xsd.GetGetCurrencyNumRqstInfo param0
    );

    @WebMethod(action = "urn:getCurrencyRate")
    @Action(input = "urn:getCurrencyRate", output = "urn:getCurrencyRateResponse")
    @RequestWrapper(localName = "getCurrencyRate", targetNamespace = "http://service.currency.cortexws.d8.lv", className = "lv.d8.cortexws.currency.service.GetCurrencyRate")
    @ResponseWrapper(localName = "getCurrencyRateResponse", targetNamespace = "http://service.currency.cortexws.d8.lv", className = "lv.d8.cortexws.currency.service.GetCurrencyRateResponse")
    @WebResult(name = "return", targetNamespace = "http://service.currency.cortexws.d8.lv")
    public lv.d8.cortexws.currency.valueobj.xsd.GetGetCurrencyRateRspsInfo getCurrencyRate(
        @WebParam(name = "param0", targetNamespace = "http://service.currency.cortexws.d8.lv")
        lv.d8.cortexws.currency.valueobj.xsd.GetGetCurrencyRateRqstInfo param0
    );

    @WebMethod(action = "urn:addCurrencyRate")
    @Action(input = "urn:addCurrencyRate", output = "urn:addCurrencyRateResponse")
    @RequestWrapper(localName = "addCurrencyRate", targetNamespace = "http://service.currency.cortexws.d8.lv", className = "lv.d8.cortexws.currency.service.AddCurrencyRate")
    @ResponseWrapper(localName = "addCurrencyRateResponse", targetNamespace = "http://service.currency.cortexws.d8.lv", className = "lv.d8.cortexws.currency.service.AddCurrencyRateResponse")
    @WebResult(name = "return", targetNamespace = "http://service.currency.cortexws.d8.lv")
    public lv.d8.cortexws.currency.valueobj.xsd.GetAddCurrencyRateRspsInfo addCurrencyRate(
        @WebParam(name = "param0", targetNamespace = "http://service.currency.cortexws.d8.lv")
        lv.d8.cortexws.currency.valueobj.xsd.GetAddCurrencyRateRqstInfo param0
    );
}
