
package gisgmp;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.4.redhat-1
 * 2017-05-15T10:12:01.706+03:00
 * Generated source version: 3.1.4.redhat-1
 */

@WebFault(name = "DSCALLFAULT", targetNamespace = "http://support.diasoft.ru")
public class DSCALLFAULT_Exception extends Exception {
    
    private gisgmp.DSCALLFAULT dscallfault;

    public DSCALLFAULT_Exception() {
        super();
    }
    
    public DSCALLFAULT_Exception(String message) {
        super(message);
    }
    
    public DSCALLFAULT_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public DSCALLFAULT_Exception(String message, gisgmp.DSCALLFAULT dscallfault) {
        super(message);
        this.dscallfault = dscallfault;
    }

    public DSCALLFAULT_Exception(String message, gisgmp.DSCALLFAULT dscallfault, Throwable cause) {
        super(message, cause);
        this.dscallfault = dscallfault;
    }

    public gisgmp.DSCALLFAULT getFaultInfo() {
        return this.dscallfault;
    }
}
