package gisgmp;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.4.redhat-1
 * 2017-05-15T10:12:01.760+03:00
 * Generated source version: 3.1.4.redhat-1
 * 
 */
@WebServiceClient(name = "FTGMPADTWSSERVICE", 
                  wsdlLocation = "http://10.1.203.17:8081/ftgmpadtws/ftgmpadtws?WSDL",
                  targetNamespace = "http://support.diasoft.ru") 
public class FTGMPADTWSSERVICE extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://support.diasoft.ru", "FTGMPADTWSSERVICE");
    public final static QName FTGMPADTWSPORT = new QName("http://support.diasoft.ru", "FTGMPADTWSPORT");
    static {
        URL url = null;
        try {
            url = new URL("http://10.1.203.17:8081/ftgmpadtws/ftgmpadtws?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(FTGMPADTWSSERVICE.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.1.203.17:8081/ftgmpadtws/ftgmpadtws?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public FTGMPADTWSSERVICE(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FTGMPADTWSSERVICE(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FTGMPADTWSSERVICE() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public FTGMPADTWSSERVICE(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public FTGMPADTWSSERVICE(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public FTGMPADTWSSERVICE(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns FTGMPADTWSPORTTYPE
     */
    @WebEndpoint(name = "FTGMPADTWSPORT")
    public FTGMPADTWSPORTTYPE getFTGMPADTWSPORT() {
        return super.getPort(FTGMPADTWSPORT, FTGMPADTWSPORTTYPE.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FTGMPADTWSPORTTYPE
     */
    @WebEndpoint(name = "FTGMPADTWSPORT")
    public FTGMPADTWSPORTTYPE getFTGMPADTWSPORT(WebServiceFeature... features) {
        return super.getPort(FTGMPADTWSPORT, FTGMPADTWSPORTTYPE.class, features);
    }

}
