package ctxdbo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4.redhat-1
 * 2017-01-11T14:20:18.542+03:00
 * Generated source version: 3.1.4.redhat-1
 * 
 */
@WebService(targetNamespace = "http://ws.wso2.org/dataservice", name = "CTX_DBOPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface CTXDBOPortType {

    @WebMethod(action = "urn:getCardSettlement")
    @Action(input = "urn:getCardSettlement", output = "urn:getCardSettlementResponse", fault = {@FaultAction(className = DataServiceFault_Exception.class, value = "urn:getCardSettlementDataServiceFault")})
    @RequestWrapper(localName = "getCardSettlement", targetNamespace = "http://ws.wso2.org/dataservice", className = "ctxdbo.GetCardSettlement")
    @ResponseWrapper(localName = "CardSettlements", targetNamespace = "http://ws.wso2.org/dataservice", className = "ctxdbo.CardSettlements")
    @WebResult(name = "CardSettlement", targetNamespace = "http://ws.wso2.org/dataservice")
    public java.util.List<ctxdbo.CardSettlement> getCardSettlement(
        @WebParam(name = "pan", targetNamespace = "http://ws.wso2.org/dataservice")
        java.lang.String pan,
        @WebParam(name = "startdate", targetNamespace = "http://ws.wso2.org/dataservice")
        java.lang.String startdate,
        @WebParam(name = "enddate", targetNamespace = "http://ws.wso2.org/dataservice")
        java.lang.String enddate
    ) throws DataServiceFault_Exception;

    @WebMethod(action = "urn:getCurrencyRate")
    @Action(input = "urn:getCurrencyRate", output = "urn:getCurrencyRateResponse", fault = {@FaultAction(className = DataServiceFault_Exception.class, value = "urn:getCurrencyRateDataServiceFault")})
    @RequestWrapper(localName = "getCurrencyRate", targetNamespace = "http://ws.wso2.org/dataservice", className = "ctxdbo.GetCurrencyRate")
    @ResponseWrapper(localName = "getCurrencyRateResponse", targetNamespace = "http://ws.wso2.org/dataservice", className = "ctxdbo.GetCurrencyRateResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.wso2.org/dataservice")
    public java.util.List<ctxdbo.Return> getCurrencyRate(
        @WebParam(name = "basecurcode", targetNamespace = "http://ws.wso2.org/dataservice")
        java.lang.String basecurcode,
        @WebParam(name = "curcode", targetNamespace = "http://ws.wso2.org/dataservice")
        java.lang.String curcode
    ) throws DataServiceFault_Exception;

    @WebMethod(action = "urn:getRRN")
    @Action(input = "urn:getRRN", output = "urn:getRRNResponse", fault = {@FaultAction(className = DataServiceFault_Exception.class, value = "urn:getRRNDataServiceFault")})
    @RequestWrapper(localName = "getRRN", targetNamespace = "http://ws.wso2.org/dataservice", className = "ctxdbo.GetRRN")
    @ResponseWrapper(localName = "Entries", targetNamespace = "http://ws.wso2.org/dataservice", className = "ctxdbo.Entries")
    @WebResult(name = "Entry", targetNamespace = "http://ws.wso2.org/dataservice")
    public java.util.List<ctxdbo.Entry> getRRN(
        @WebParam(name = "tlogid", targetNamespace = "http://ws.wso2.org/dataservice")
        java.lang.String tlogid
    ) throws DataServiceFault_Exception;
}
