
package ctxdbo;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.4.redhat-1
 * 2017-01-11T14:20:18.523+03:00
 * Generated source version: 3.1.4.redhat-1
 */

@WebFault(name = "DataServiceFault", targetNamespace = "http://ws.wso2.org/dataservice")
public class DataServiceFault_Exception extends Exception {
    
    private ctxdbo.DataServiceFault dataServiceFault;

    public DataServiceFault_Exception() {
        super();
    }
    
    public DataServiceFault_Exception(String message) {
        super(message);
    }
    
    public DataServiceFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public DataServiceFault_Exception(String message, ctxdbo.DataServiceFault dataServiceFault) {
        super(message);
        this.dataServiceFault = dataServiceFault;
    }

    public DataServiceFault_Exception(String message, ctxdbo.DataServiceFault dataServiceFault, Throwable cause) {
        super(message, cause);
        this.dataServiceFault = dataServiceFault;
    }

    public ctxdbo.DataServiceFault getFaultInfo() {
        return this.dataServiceFault;
    }
}
