package ru.bpc.apigate;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.4.redhat-1
 * 2018-03-16T11:47:29.488+03:00
 * Generated source version: 3.1.4.redhat-1
 * 
 */
@WebService(targetNamespace = "http://www.bpc.ru/apigate/", name = "apigate")
@XmlSeeAlso({ru.bpc.apigate.command.changeaccountlimit.ObjectFactory.class, ru.bpc.apigate.command.reversal.ObjectFactory.class, ru.bpc.apigate.command.getcardlistbyowner.ObjectFactory.class, ru.bpc.apigate.command.createvirtualcard.ObjectFactory.class, ru.bpc.apigate.command.creditcard.ObjectFactory.class, ru.bpc.apigate.command.changepin.ObjectFactory.class, ru.bpc.apigate.command.p2ptransfer.ObjectFactory.class, ru.bpc.apigate.command.getcardbalance.ObjectFactory.class, ru.bpc.apigate.command.activatecard.ObjectFactory.class, ru.bpc.apigate.command.getcardlimits.ObjectFactory.class, ru.bpc.apigate.command.ministatement.ObjectFactory.class, ru.bpc.apigate.errors.ObjectFactory.class, ru.bpc.apigate.command.getcarddata.ObjectFactory.class, ru.bpc.apigate.command.purchase.ObjectFactory.class, ru.bpc.apigate.command.generatepin.ObjectFactory.class, ru.bpc.apigate.command.changecardstatus.ObjectFactory.class, ru.bpc.apigate.command.gettransactions.ObjectFactory.class, ru.bpc.apigate.general.ObjectFactory.class, ru.bpc.apigate.command.getaccountdata.ObjectFactory.class, ru.bpc.apigate.command.blockcard.ObjectFactory.class, ru.bpc.apigate.command.serviceaction.ObjectFactory.class, ru.bpc.apigate.command.addcardlimitexception.ObjectFactory.class, ru.bpc.apigate.command.resetpincounter.ObjectFactory.class, ru.bpc.apigate.command.checkcard.ObjectFactory.class, ru.bpc.apigate.command.cardstatusinquiry.ObjectFactory.class, ru.bpc.apigate.command.changecardlimit.ObjectFactory.class, ru.bpc.apigate.command.validatecard.ObjectFactory.class, ru.bpc.apigate.command.bindcardtoaccount.ObjectFactory.class, ru.bpc.apigate.command.debitcard.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Apigate {

    @WebMethod(operationName = "p2pTransfer", action = "http://www.bpc.ru/apigate/p2pTransfer")
    @WebResult(name = "p2pTransferResponse", targetNamespace = "http://www.bpc.ru/apigate/command/p2pTransfer/", partName = "parameters")
    public ru.bpc.apigate.general.FinancialTransactionResponseType p2PTransfer(
        @WebParam(partName = "parameters", name = "p2pTransferRequest", targetNamespace = "http://www.bpc.ru/apigate/command/p2pTransfer/")
        ru.bpc.apigate.command.p2ptransfer.P2PTransferRequestType parameters
    ) throws SvfeProcessingException, ServiceLevelException;

    @WebMethod(action = "http://www.bpc.ru/apigate/changeAccountLimit")
    @WebResult(name = "changeAccountLimitResponse", targetNamespace = "http://www.bpc.ru/apigate/command/changeAccountLimit/", partName = "parameters")
    public ru.bpc.apigate.general.SimpleResponseType changeAccountLimit(
        @WebParam(partName = "parameters", name = "changeAccountLimitRequest", targetNamespace = "http://www.bpc.ru/apigate/command/changeAccountLimit/")
        ru.bpc.apigate.command.changeaccountlimit.ChangeAccountLimitRequestType parameters
    ) throws SvfeProcessingException, ServiceLevelException;

    @WebMethod(action = "http://www.bpc.ru/apigate/reversal")
    @WebResult(name = "reversalResponse", targetNamespace = "http://www.bpc.ru/apigate/command/reversal/", partName = "parameters")
    public ru.bpc.apigate.command.reversal.ReversalResponseType reversal(
        @WebParam(partName = "parameters", name = "reversalRequest", targetNamespace = "http://www.bpc.ru/apigate/command/reversal/")
        ru.bpc.apigate.command.reversal.ReversalRequestType parameters
    ) throws SvfeProcessingException, ServiceLevelException;

    @WebMethod(action = "http://www.bpc.ru/apigate/cardStatusInquiry")
    @WebResult(name = "cardStatusInquiryResponse", targetNamespace = "http://www.bpc.ru/apigate/command/cardStatusInquiry/", partName = "parameters")
    public ru.bpc.apigate.command.cardstatusinquiry.CardStatusInquiryResponseType cardStatusInquiry(
        @WebParam(partName = "parameters", name = "cardStatusInquiryRequest", targetNamespace = "http://www.bpc.ru/apigate/command/cardStatusInquiry/")
        ru.bpc.apigate.command.cardstatusinquiry.CardStatusInquiryRequestType parameters
    ) throws SvfeProcessingException, ServiceLevelException;

    @WebMethod(action = "http://www.bpc.ru/apigate/changePin")
    @WebResult(name = "changePinResponse", targetNamespace = "http://www.bpc.ru/apigate/command/changePin/", partName = "parameters")
    public ru.bpc.apigate.general.SimpleResponseType changePin(
        @WebParam(partName = "parameters", name = "changePinRequest", targetNamespace = "http://www.bpc.ru/apigate/command/changePin/")
        ru.bpc.apigate.command.changepin.ChangePinRequestType parameters
    ) throws SvfeProcessingException, ServiceLevelException;

    @WebMethod(action = "http://www.bpc.ru/apigate/debitCard")
    @WebResult(name = "debitCardResponse", targetNamespace = "http://www.bpc.ru/apigate/command/debitCard/", partName = "parameters")
    public ru.bpc.apigate.general.FinancialTransactionResponseType debitCard(
        @WebParam(partName = "parameters", name = "debitCardRequest", targetNamespace = "http://www.bpc.ru/apigate/command/debitCard/")
        ru.bpc.apigate.command.debitcard.DebitCardRequestType parameters
    ) throws SvfeProcessingException, ServiceLevelException;

    @WebMethod(action = "http://www.bpc.ru/apigate/serviceAction")
    @WebResult(name = "serviceActionResponse", targetNamespace = "http://www.bpc.ru/apigate/command/serviceAction/", partName = "parameters")
    public ru.bpc.apigate.general.SimpleResponseType serviceAction(
        @WebParam(partName = "parameters", name = "serviceActionRequest", targetNamespace = "http://www.bpc.ru/apigate/command/serviceAction/")
        ru.bpc.apigate.command.serviceaction.ServiceActionRequestType parameters
    ) throws SvfeProcessingException, ServiceLevelException;

    @WebMethod(action = "http://www.bpc.ru/apigate/generatePin")
    @WebResult(name = "generatePinResponse", targetNamespace = "http://www.bpc.ru/apigate/command/generatePin/", partName = "parameters")
    public ru.bpc.apigate.command.generatepin.GeneratePinResponseType generatePin(
        @WebParam(partName = "parameters", name = "generatePinRequest", targetNamespace = "http://www.bpc.ru/apigate/command/generatePin/")
        ru.bpc.apigate.command.generatepin.GeneratePinRequestType parameters
    ) throws SvfeProcessingException, ServiceLevelException;

    @WebMethod(action = "http://www.bpc.ru/apigate/creditCard")
    @WebResult(name = "creditCardResponse", targetNamespace = "http://www.bpc.ru/apigate/command/creditCard/", partName = "parameters")
    public ru.bpc.apigate.general.FinancialTransactionResponseType creditCard(
        @WebParam(partName = "parameters", name = "creditCardRequest", targetNamespace = "http://www.bpc.ru/apigate/command/creditCard/")
        ru.bpc.apigate.command.creditcard.CreditCardRequestType parameters
    ) throws SvfeProcessingException, ServiceLevelException;

    @WebMethod(action = "http://www.bpc.ru/apigate/getCardBalance")
    @WebResult(name = "getCardBalanceResponse", targetNamespace = "http://www.bpc.ru/apigate/command/getCardBalance/", partName = "parameters")
    public ru.bpc.apigate.command.getcardbalance.GetCardBalanceResponseType getCardBalance(
        @WebParam(partName = "parameters", name = "getCardBalanceRequest", targetNamespace = "http://www.bpc.ru/apigate/command/getCardBalance/")
        ru.bpc.apigate.command.getcardbalance.GetCardBalanceRequestType parameters
    ) throws SvfeProcessingException, ServiceLevelException;

    @WebMethod(action = "http://www.bpc.ru/apigate/activateCard")
    @WebResult(name = "activateCardResponse", targetNamespace = "http://www.bpc.ru/apigate/command/activateCard/", partName = "parameters")
    public ru.bpc.apigate.general.SimpleResponseType activateCard(
        @WebParam(partName = "parameters", name = "activateCardRequest", targetNamespace = "http://www.bpc.ru/apigate/command/activateCard/")
        ru.bpc.apigate.command.activatecard.ActivateCardRequestType parameters
    ) throws SvfeProcessingException, ServiceLevelException;

    @WebMethod(action = "http://www.bpc.ru/apigate/createVirtualCard")
    @WebResult(name = "createVirtualCardResponse", targetNamespace = "http://www.bpc.ru/apigate/command/createVirtualCard/", partName = "parameters")
    public ru.bpc.apigate.command.createvirtualcard.CreateVirtualCardResponseType createVirtualCard(
        @WebParam(partName = "parameters", name = "createVirtualCardRequest", targetNamespace = "http://www.bpc.ru/apigate/command/createVirtualCard/")
        ru.bpc.apigate.command.createvirtualcard.CreateVirtualCardRequestType parameters
    ) throws SvfeProcessingException, ServiceLevelException;

    @WebMethod(action = "http://www.bpc.ru/apigate/getTransactions")
    @WebResult(name = "getTransactionsResponse", targetNamespace = "http://www.bpc.ru/apigate/command/getTransactions/", partName = "parameters")
    public ru.bpc.apigate.command.gettransactions.GetTransactionsResponseType getTransactions(
        @WebParam(partName = "parameters", name = "getTransactionsRequest", targetNamespace = "http://www.bpc.ru/apigate/command/getTransactions/")
        ru.bpc.apigate.command.gettransactions.GetTransactionsRequestType parameters
    ) throws SvfeProcessingException, ServiceLevelException;

    @WebMethod(action = "http://www.bpc.ru/apigate/purchase")
    @WebResult(name = "purchaseResponse", targetNamespace = "http://www.bpc.ru/apigate/command/purchase/", partName = "parameters")
    public ru.bpc.apigate.general.FinancialTransactionResponseType purchase(
        @WebParam(partName = "parameters", name = "purchaseRequest", targetNamespace = "http://www.bpc.ru/apigate/command/purchase/")
        ru.bpc.apigate.command.purchase.PurchaseRequestType parameters
    ) throws SvfeProcessingException, ServiceLevelException;

    @WebMethod(action = "http://www.bpc.ru/apigate/miniStatement")
    @WebResult(name = "miniStatementResponse", targetNamespace = "http://www.bpc.ru/apigate/command/miniStatement/", partName = "parameters")
    public ru.bpc.apigate.command.ministatement.MiniStatementResponseType miniStatement(
        @WebParam(partName = "parameters", name = "miniStatementRequest", targetNamespace = "http://www.bpc.ru/apigate/command/miniStatement/")
        ru.bpc.apigate.command.ministatement.MiniStatementRequestType parameters
    ) throws SvfeProcessingException, ServiceLevelException;

    @WebMethod(action = "http://www.bpc.ru/apigate/validateCard")
    @WebResult(name = "validateCardResponse", targetNamespace = "http://www.bpc.ru/apigate/command/validateCard/", partName = "parameters")
    public ru.bpc.apigate.general.SimpleResponseType validateCard(
        @WebParam(partName = "parameters", name = "validateCardRequest", targetNamespace = "http://www.bpc.ru/apigate/command/validateCard/")
        ru.bpc.apigate.command.validatecard.ValidateCardRequestType parameters
    ) throws SvfeProcessingException, ServiceLevelException;

    @WebMethod(action = "http://www.bpc.ru/apigate/getAccountData")
    @WebResult(name = "getAccountDataResponse", targetNamespace = "http://www.bpc.ru/apigate/command/getAccountData/", partName = "parameters")
    public ru.bpc.apigate.command.getaccountdata.GetAccountDataResponseType getAccountData(
        @WebParam(partName = "parameters", name = "getAccountDataRequest", targetNamespace = "http://www.bpc.ru/apigate/command/getAccountData/")
        ru.bpc.apigate.command.getaccountdata.GetAccountDataRequestType parameters
    ) throws SvfeProcessingException, ServiceLevelException;

    @WebMethod(action = "http://www.bpc.ru/apigate/changeCardStatus")
    @WebResult(name = "changeCardStatusResponse", targetNamespace = "http://www.bpc.ru/apigate/command/changeCardStatus/", partName = "parameters")
    public ru.bpc.apigate.general.SimpleResponseType changeCardStatus(
        @WebParam(partName = "parameters", name = "changeCardStatusRequest", targetNamespace = "http://www.bpc.ru/apigate/command/changeCardStatus/")
        ru.bpc.apigate.general.ChangeCardStatusRequestType parameters
    ) throws SvfeProcessingException, ServiceLevelException;

    @WebMethod(action = "http://www.bpc.ru/apigate/checkCard")
    @WebResult(name = "checkCardResponse", targetNamespace = "http://www.bpc.ru/apigate/command/checkCard/", partName = "parameters")
    public ru.bpc.apigate.command.checkcard.CheckCardRequestResponseType checkCard(
        @WebParam(partName = "parameters", name = "checkCardRequest", targetNamespace = "http://www.bpc.ru/apigate/command/checkCard/")
        ru.bpc.apigate.command.checkcard.CheckCardRequestRequestType parameters
    ) throws SvfeProcessingException, ServiceLevelException;

    @WebMethod(action = "http://www.bpc.ru/apigate/blockCard")
    @WebResult(name = "blockCardResponse", targetNamespace = "http://www.bpc.ru/apigate/command/blockCard/", partName = "parameters")
    public ru.bpc.apigate.general.SimpleResponseType blockCard(
        @WebParam(partName = "parameters", name = "blockCardRequest", targetNamespace = "http://www.bpc.ru/apigate/command/blockCard/")
        ru.bpc.apigate.general.ChangeCardStatusRequestType parameters
    ) throws SvfeProcessingException, ServiceLevelException;

    @WebMethod(action = "http://www.bpc.ru/apigate/addCardLimitException")
    @WebResult(name = "addCardLimitExceptionResponse", targetNamespace = "http://www.bpc.ru/apigate/command/addCardLimitException/", partName = "parameters")
    public ru.bpc.apigate.general.SimpleResponseType addCardLimitException(
        @WebParam(partName = "parameters", name = "addCardLimitExceptionRequest", targetNamespace = "http://www.bpc.ru/apigate/command/addCardLimitException/")
        ru.bpc.apigate.command.addcardlimitexception.AddCardLimitExceptionRequestType parameters
    ) throws SvfeProcessingException, ServiceLevelException;

    @WebMethod(action = "http://www.bpc.ru/apigate/getCardData")
    @WebResult(name = "getCardDataResponse", targetNamespace = "http://www.bpc.ru/apigate/command/getCardData/", partName = "parameters")
    public ru.bpc.apigate.command.getcarddata.GetCardDataResponseType getCardData(
        @WebParam(partName = "parameters", name = "getCardDataRequest", targetNamespace = "http://www.bpc.ru/apigate/command/getCardData/")
        ru.bpc.apigate.command.getcarddata.GetCardDataRequestType parameters
    ) throws SvfeProcessingException, ServiceLevelException;

    @WebMethod(action = "http://www.bpc.ru/apigate/changeCardLimit")
    @WebResult(name = "changeCardLimitResponse", targetNamespace = "http://www.bpc.ru/apigate/command/changeCardLimit/", partName = "parameters")
    public ru.bpc.apigate.general.SimpleResponseType changeCardLimit(
        @WebParam(partName = "parameters", name = "changeCardLimitRequest", targetNamespace = "http://www.bpc.ru/apigate/command/changeCardLimit/")
        ru.bpc.apigate.command.changecardlimit.ChangeCardLimitRequestType parameters
    ) throws SvfeProcessingException, ServiceLevelException;

    @WebMethod(action = "http://www.bpc.ru/apigate/resetPinCounter")
    @WebResult(name = "resetPinCounterResponse", targetNamespace = "http://www.bpc.ru/apigate/command/resetPinCounter/", partName = "parameters")
    public ru.bpc.apigate.general.SimpleResponseType resetPinCounter(
        @WebParam(partName = "parameters", name = "resetPinCounterRequest", targetNamespace = "http://www.bpc.ru/apigate/command/resetPinCounter/")
        ru.bpc.apigate.command.resetpincounter.ResetPinCounterRequestType parameters
    ) throws SvfeProcessingException, ServiceLevelException;

    @WebMethod(action = "http://www.bpc.ru/apigate/getCardLimits")
    @WebResult(name = "getCardLimitsResponse", targetNamespace = "http://www.bpc.ru/apigate/command/getCardLimits/", partName = "parameters")
    public ru.bpc.apigate.command.getcardlimits.GetCardLimitsResponseType getCardLimits(
        @WebParam(partName = "parameters", name = "getCardLimitsRequest", targetNamespace = "http://www.bpc.ru/apigate/command/getCardLimits/")
        ru.bpc.apigate.command.getcardlimits.GetCardLimitsRequestType parameters
    ) throws SvfeProcessingException, ServiceLevelException;

    @WebMethod(action = "http://www.bpc.ru/apigate/getCardListByOwner")
    @WebResult(name = "getCardListByOwnerResponse", targetNamespace = "http://www.bpc.ru/apigate/command/getCardListByOwner/", partName = "parameters")
    public ru.bpc.apigate.command.getcardlistbyowner.GetCardListByOwnerResponseType getCardListByOwner(
        @WebParam(partName = "parameters", name = "getCardListByOwnerRequest", targetNamespace = "http://www.bpc.ru/apigate/command/getCardListByOwner/")
        ru.bpc.apigate.command.getcardlistbyowner.GetCardListByOwnerRequestType parameters
    ) throws SvfeProcessingException, ServiceLevelException;

    @WebMethod(action = "http://www.bpc.ru/apigate/bindCardToAccount")
    @WebResult(name = "bindCardToAccountResponse", targetNamespace = "http://www.bpc.ru/apigate/command/bindCardToAccount/", partName = "parameters")
    public ru.bpc.apigate.general.SimpleResponseType bindCardToAccount(
        @WebParam(partName = "parameters", name = "bindCardToAccountRequest", targetNamespace = "http://www.bpc.ru/apigate/command/bindCardToAccount/")
        ru.bpc.apigate.command.bindcardtoaccount.BindCardToAccountRequestType parameters
    ) throws SvfeProcessingException, ServiceLevelException;
}
