
package ru.bpc.apigate;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.4.redhat-1
 * 2018-03-16T11:47:29.484+03:00
 * Generated source version: 3.1.4.redhat-1
 */

@WebFault(name = "serviceLevelFault", targetNamespace = "http://www.bpc.ru/apigate/errors/")
public class ServiceLevelException extends Exception {
    
    private ru.bpc.apigate.errors.ServiceLevelFaultType serviceLevelFault;

    public ServiceLevelException() {
        super();
    }
    
    public ServiceLevelException(String message) {
        super(message);
    }
    
    public ServiceLevelException(String message, Throwable cause) {
        super(message, cause);
    }

    public ServiceLevelException(String message, ru.bpc.apigate.errors.ServiceLevelFaultType serviceLevelFault) {
        super(message);
        this.serviceLevelFault = serviceLevelFault;
    }

    public ServiceLevelException(String message, ru.bpc.apigate.errors.ServiceLevelFaultType serviceLevelFault, Throwable cause) {
        super(message, cause);
        this.serviceLevelFault = serviceLevelFault;
    }

    public ru.bpc.apigate.errors.ServiceLevelFaultType getFaultInfo() {
        return this.serviceLevelFault;
    }
}
