package svdbo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4.redhat-1
 * 2018-02-13T12:30:38.969+03:00
 * Generated source version: 3.1.4.redhat-1
 * 
 */
@WebService(targetNamespace = "http://ws.wso2.org/dataservice", name = "SV_DBOPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface SVDBOPortType {

    @WebMethod(action = "urn:getCurrencyRate")
    @Action(input = "urn:getCurrencyRate", output = "urn:getCurrencyRateResponse", fault = {@FaultAction(className = DataServiceFault_Exception.class, value = "urn:getCurrencyRateDataServiceFault")})
    @RequestWrapper(localName = "getCurrencyRate", targetNamespace = "http://ws.wso2.org/dataservice", className = "svdbo.GetCurrencyRate")
    @ResponseWrapper(localName = "getCurrencyRateResponse", targetNamespace = "http://ws.wso2.org/dataservice", className = "svdbo.GetCurrencyRateResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.wso2.org/dataservice")
    public java.util.List<svdbo.Return> getCurrencyRate(
        @WebParam(name = "basecurcode", targetNamespace = "http://ws.wso2.org/dataservice")
        java.lang.String basecurcode,
        @WebParam(name = "curcode", targetNamespace = "http://ws.wso2.org/dataservice")
        java.lang.String curcode
    ) throws DataServiceFault_Exception;
}
