package giszhkhsrv;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.4.redhat-1
 * 2017-05-15T14:11:25.397+03:00
 * Generated source version: 3.1.4.redhat-1
 * 
 */
@WebServiceClient(name = "FTGISZHKHREQPROCWSSERVICE", 
                  wsdlLocation = "http://10.1.203.17:8081/ftgiszhkhreqprocws/ftgiszhkhreqprocws?WSDL",
                  targetNamespace = "http://support.diasoft.ru") 
public class FTGISZHKHREQPROCWSSERVICE extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://support.diasoft.ru", "FTGISZHKHREQPROCWSSERVICE");
    public final static QName FTGISZHKHREQPROCWSPORT = new QName("http://support.diasoft.ru", "FTGISZHKHREQPROCWSPORT");
    static {
        URL url = null;
        try {
            url = new URL("http://10.1.203.17:8081/ftgiszhkhreqprocws/ftgiszhkhreqprocws?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(FTGISZHKHREQPROCWSSERVICE.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.1.203.17:8081/ftgiszhkhreqprocws/ftgiszhkhreqprocws?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public FTGISZHKHREQPROCWSSERVICE(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FTGISZHKHREQPROCWSSERVICE(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FTGISZHKHREQPROCWSSERVICE() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public FTGISZHKHREQPROCWSSERVICE(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public FTGISZHKHREQPROCWSSERVICE(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public FTGISZHKHREQPROCWSSERVICE(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns FTGISZHKHREQPROCWSPORTTYPE
     */
    @WebEndpoint(name = "FTGISZHKHREQPROCWSPORT")
    public FTGISZHKHREQPROCWSPORTTYPE getFTGISZHKHREQPROCWSPORT() {
        return super.getPort(FTGISZHKHREQPROCWSPORT, FTGISZHKHREQPROCWSPORTTYPE.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FTGISZHKHREQPROCWSPORTTYPE
     */
    @WebEndpoint(name = "FTGISZHKHREQPROCWSPORT")
    public FTGISZHKHREQPROCWSPORTTYPE getFTGISZHKHREQPROCWSPORT(WebServiceFeature... features) {
        return super.getPort(FTGISZHKHREQPROCWSPORT, FTGISZHKHREQPROCWSPORTTYPE.class, features);
    }

}
