package giszhkhsrv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.4.redhat-1
 * 2017-05-15T14:11:25.360+03:00
 * Generated source version: 3.1.4.redhat-1
 * 
 */
@WebService(targetNamespace = "http://support.diasoft.ru", name = "FTGISZHKHREQPROCWSPORTTYPE")
@XmlSeeAlso({ObjectFactory.class})
public interface FTGISZHKHREQPROCWSPORTTYPE {

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "ExportPaymentDocumentDetails", targetNamespace = "http://smev.gosuslugi.ru/rev120315", partName = "response")
    public ExportPaymentDocumentDetails dsGISZHKHChargeFindListByParam(
        @WebParam(partName = "request", name = "dsPaymentDocumentDetailsRequest", targetNamespace = "http://support.diasoft.ru")
        DsPaymentDocumentDetailsRequest request
    );
/*
    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "dsGISZHKHPaymentNotificationInsertAsyncResp", targetNamespace = "http://support.diasoft.ru", partName = "response")
    public DsGISZHKHPaymentNotificationInsertAsyncResp dsGISZHKHPaymentNotificationInsertAsync(
        @WebParam(partName = "request", name = "importNotificationsOfOrderExecution", targetNamespace = "http://smev.gosuslugi.ru/rev120315")
        ImportNotificationsOfOrderExecution request
    );

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "dsGISZHKHPackPaymentNotificationInsertAsyncResp", targetNamespace = "http://support.diasoft.ru", partName = "response")
    public DsGISZHKHPackPaymentNotificationInsertAsyncResp dsGISZHKHPackPaymentNotificationInsertAsync(
        @WebParam(partName = "request", name = "dsGISZHKHPackPaymentNotificationInsertAsyncReq", targetNamespace = "http://support.diasoft.ru")
        DsGISZHKHPackPaymentNotificationInsertAsyncReq request
    );

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "dsGISZHKHSinglePaymentNotificationInsertAsyncResp", targetNamespace = "http://support.diasoft.ru", partName = "response")
    public DsGISZHKHPaymentNotificationInsertAsyncResp dsGISZHKHSinglePaymentNotificationInsertAsync(
        @WebParam(partName = "request", name = "dsGISZHKHSinglePaymentNotificationInsertAsyncReq", targetNamespace = "http://support.diasoft.ru")
        DsGISZHKHSinglePaymentNotificationInsertAsyncReq request
    );

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "dsGISZHKHRecipientListByParamResp", targetNamespace = "http://support.diasoft.ru", partName = "response")
    public DsGISZHKHRecipientListByParamResp dsGISZHKHRecipientListByParam(
        @WebParam(partName = "request", name = "dsGISZHKHRecipientListByParamReq", targetNamespace = "http://support.diasoft.ru")
        DsGISZHKHRecipientListByParamReq request
    );

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "CommonResult", targetNamespace = "http://smev.gosuslugi.ru/rev120315", partName = "response")
    public CommonResult dsGISZHKHPaymentNotificationGetByID(
        @WebParam(partName = "request", name = "dsGISZHKHPaymentNotificationGetByIDReq", targetNamespace = "http://support.diasoft.ru")
        DsGISZHKHPaymentNotificationGetByIDReq request
    );

    @WebMethod(operationName = "DSCALL")
    @RequestWrapper(localName = "DSCALL", targetNamespace = "http://support.diasoft.ru", className = "giszhkhsrv.DSCALL")
    @ResponseWrapper(localName = "DSCALLRESPONSE", targetNamespace = "http://support.diasoft.ru", className = "giszhkhsrv.DSCALLRESPONSE")
    @WebResult(name = "commandresult", targetNamespace = "http://support.diasoft.ru")
    public java.lang.String dscall(
        @WebParam(name = "commandtext", targetNamespace = "http://support.diasoft.ru")
        java.lang.String commandtext,
        @WebParam(name = "commanddata", targetNamespace = "http://support.diasoft.ru")
        java.lang.String commanddata
    ) throws DSCALLFAULT_Exception;

    @WebMethod(operationName = "DSCALLASYNC")
    @Oneway
    @RequestWrapper(localName = "DSCALLASYNC", targetNamespace = "http://support.diasoft.ru", className = "giszhkhsrv.DSCALLASYNC")
    public void dscallasync(
        @WebParam(name = "commandtext", targetNamespace = "http://support.diasoft.ru")
        java.lang.String commandtext,
        @WebParam(name = "commanddata", targetNamespace = "http://support.diasoft.ru")
        java.lang.String commanddata
    );

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "dsGISZHKHSinglePaymentNotificationGetByIDResp", targetNamespace = "http://support.diasoft.ru", partName = "response")
    public DsGISZHKHSinglePaymentNotificationGetByIDResp dsGISZHKHSinglePaymentNotificationGetByID(
        @WebParam(partName = "request", name = "dsGISZHKHSinglePaymentNotificationGetByIDReq", targetNamespace = "http://support.diasoft.ru")
        DsGISZHKHPaymentNotificationGetByIDReq request
    );

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "dsGISZHKHPackPaymentNotificationGetByIDResp", targetNamespace = "http://support.diasoft.ru", partName = "response")
    public DsGISZHKHPackPaymentNotificationGetByIDResp dsGISZHKHPackPaymentNotificationGetByID(
        @WebParam(partName = "request", name = "dsGISZHKHPackPaymentNotificationGetByIDReq", targetNamespace = "http://support.diasoft.ru")
        DsGISZHKHPackPaymentNotificationGetByIDReq request
    );

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "dsGISZHKHRecipientDirectoryResp", targetNamespace = "http://support.diasoft.ru", partName = "response")
    public DsGISZHKHRecipientDirectoryResp dsGISZHKHRecipientDirectory(
        @WebParam(partName = "request", name = "dsGISZHKHRecipientDirectoryReq", targetNamespace = "http://support.diasoft.ru")
        DsGISZHKHRecipientDirectoryReq request
    );
    */
}
