package com.custsystems.integration.abs.absinterface;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.custsystems.integration.abs.DepositBO;
import com.custsystems.integration.abs.DepositResponse;

/**
 * This class was generated by Apache CXF 3.1.4.redhat-1
 * 2017-07-07T13:25:08.532+03:00
 * Generated source version: 3.1.4.redhat-1
 * 
 */
@WebService(targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", name = "ABSInterfacePortType")
@XmlSeeAlso({com.custsystems.integration.abs.ObjectFactory.class, ObjectFactory.class})
public interface ABSInterfacePortType {

    @WebMethod
    @RequestWrapper(localName = "cconv", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.Cconv")
    @ResponseWrapper(localName = "cconvResponse", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.CconvResponse")
    @WebResult(name = "response", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
    public com.custsystems.integration.abs.CConvResponse cconv(
        @WebParam(name = "request", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
        com.custsystems.integration.abs.CConvBO request
    ) throws CconvFaultMsg;

    /**
     * получение списка счетов клиента (UL, FL)
     */
    @WebMethod
    @RequestWrapper(localName = "accountList", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.AccountList")
    @ResponseWrapper(localName = "accountListResponse", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.AccountListResponse")
    @WebResult(name = "response", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
    public com.custsystems.integration.abs.AccountListResponse accountList(
        @WebParam(name = "request", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
        com.custsystems.integration.abs.AccountListBO request
    ) throws AccountListFaultMsg;

    /**
     * получение списка карт клиента (FL)
     */
    @WebMethod
    @RequestWrapper(localName = "cardList", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.CardList")
    @ResponseWrapper(localName = "cardListResponse", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.CardListResponse")
    @WebResult(name = "response", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
    public com.custsystems.integration.abs.CardListResponse cardList(
        @WebParam(name = "request", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
        com.custsystems.integration.abs.CardListBO request
    ) throws CardListFaultMsg;

    /**
     * заявление на досрочное расторжение вклада (FL)
     */
    @WebMethod
    @RequestWrapper(localName = "closeDeposit", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.CloseDeposit")
    @ResponseWrapper(localName = "closeDepositResponse", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.CloseDepositResponse")
    @WebResult(name = "response", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
    public com.custsystems.integration.abs.CloseDepositResponse closeDeposit(
        @WebParam(name = "request", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
        com.custsystems.integration.abs.CloseDepositBO request
    ) throws CloseDepositFaultMsg;

    /**
     * получение информации по физ. лицу (FL)
     */
    @WebMethod
    @RequestWrapper(localName = "cust", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.Cust")
    @ResponseWrapper(localName = "custResponse", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.CustResponse")
    @WebResult(name = "response", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
    public com.custsystems.integration.abs.CustResponse cust(
        @WebParam(name = "request", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
        com.custsystems.integration.abs.CustBO request
    ) throws CustFaultMsg;

    /**
     * рублевый перевод внутри/за пределы банка (FL)
     */
    @WebMethod
    @RequestWrapper(localName = "pdr", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.Pdr")
    @ResponseWrapper(localName = "pdrResponse", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.PdrResponse")
    @WebResult(name = "response", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
    public com.custsystems.integration.abs.PDRResponse pdr(
        @WebParam(name = "request", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
        com.custsystems.integration.abs.PDRBO request
    ) throws PdrFaultMsg;

    /**
     * проверка статуса заявления на открытие вклада (FL)
     */
    @WebMethod
    @RequestWrapper(localName = "openDepositStatus", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.OpenDepositStatus")
    @ResponseWrapper(localName = "openDepositStatusResponse", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.OpenDepositStatusResponse")
    @WebResult(name = "response", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
    public com.custsystems.integration.abs.OpenDepositStatusResponse openDepositStatus(
        @WebParam(name = "request", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
        com.custsystems.integration.abs.OpenDepositStatusRequest request
    ) throws OpenDepositStatusFaultMsg;

    /**
     * получение номера клиента владельца карты (FL)
     */
    @WebMethod
    @RequestWrapper(localName = "cardCust", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.CardCust")
    @ResponseWrapper(localName = "cardCustResponse", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.CardCustResponse")
    @WebResult(name = "response", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
    public com.custsystems.integration.abs.CardCustResponse cardCust(
        @WebParam(name = "request", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
        com.custsystems.integration.abs.CardCustBO request
    ) throws CardCustFaultMsg;

    /**
     * отзыв ранее выгруженного заявления на открытие депозита (UL, FL)
     */
    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "contractDepositCancelResponse", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", partName = "contractDepositCancelResult")
    public ContractDepositCancelResponse contractDepositCancel(
        @WebParam(partName = "contractDepositCancelParameters", name = "contractDepositCancelRequest", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
        ContractDepositCancelRequest contractDepositCancelParameters
    ) throws ContractDepositCancelFaultMsg;

    /**
     * Получение информации по юридическому лицу
     */
    @WebMethod
    @RequestWrapper(localName = "companyInfo", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.CompanyInfo")
    @ResponseWrapper(localName = "companyInfoResponse", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.CompanyInfoResponse")
    @WebResult(name = "response", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
    public com.custsystems.integration.abs.CompanyInfoResponse companyInfo(
        @WebParam(name = "request", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
        com.custsystems.integration.abs.CompanyInfoRequest request
    ) throws CompanyInfoFaultMessage;

    /**
     * Получение информации о клиенте по номеру телефона
     */
    @WebMethod
    @RequestWrapper(localName = "clientInfoByPhone", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.ClientInfoByPhone")
    @ResponseWrapper(localName = "clientInfoByPhoneResponse", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.ClientInfoByPhoneResponse")
    @WebResult(name = "response", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
    public com.custsystems.integration.abs.ClientInfoByPhoneResponse clientInfoByPhone(
        @WebParam(name = "request", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
        com.custsystems.integration.abs.ClientInfoByPhoneRequest request
    ) throws ClientInfoByPhoneFaultMsg;

    /**
     * оплата услуг (FL)
     */
    @WebMethod
    @RequestWrapper(localName = "pupay", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.Pupay")
    @ResponseWrapper(localName = "pupayResponse", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.PupayResponse")
    @WebResult(name = "response", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
    public com.custsystems.integration.abs.PupayResponse pupay(
        @WebParam(name = "request", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
        com.custsystems.integration.abs.PupayBO request
    ) throws PupayFaultMsg;

    /**
     * Получение информации по номеру карты (кастомизация хлынова)
     */
    @WebMethod
    @RequestWrapper(localName = "cardInfo", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.CardInfo")
    @ResponseWrapper(localName = "cardInfoResponse", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.CardInfoResponse")
    @WebResult(name = "response", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
    public com.custsystems.integration.abs.CardInfoRequestResponse cardInfo(
        @WebParam(name = "request", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
        com.custsystems.integration.abs.CardInfoRequest request
    ) throws CardInfoFaultMsg;

    /**
     * получение выписки по счетам (UL, FL)
     */
    @WebMethod
    @RequestWrapper(localName = "stm", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.Stm")
    @ResponseWrapper(localName = "stmResponse", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.StmResponse")
    @WebResult(name = "response", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
    public com.custsystems.integration.abs.StmResponse stm(
        @WebParam(name = "request", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
        com.custsystems.integration.abs.StmBO request
    ) throws StmFaultMsg;

    /**
     * получение списка кредитов клиента (UL, FL)
     */
    @WebMethod
    @RequestWrapper(localName = "creditList", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.CreditList")
    @ResponseWrapper(localName = "creditListResponse", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.CreditListResponse")
    @WebResult(name = "response", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
    public com.custsystems.integration.abs.CreditListResponse creditList(
        @WebParam(name = "request", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
        com.custsystems.integration.abs.CreditListBO request
    ) throws CreditListFaultMsg;

    /**
     * Отправка письма ЮЛ в банк
     */
    @WebMethod(operationName = "mail2bankUL")
    @RequestWrapper(localName = "mail2bankUL", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.Mail2BankUL")
    @ResponseWrapper(localName = "mail2bankULResponse", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.Mail2BankULResponse")
    @WebResult(name = "response", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
    public com.custsystems.integration.abs.Mail2BankULResponse mail2BankUL(
        @WebParam(name = "request", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
        com.custsystems.integration.abs.Mail2BankULRequest request
    ) throws Mail2BankULFaultMessage;

    /**
     * паспорт сделки по кредитному договору (UL)
     */
    @WebMethod
    @RequestWrapper(localName = "dealPassCredit", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.DealPassCredit")
    @ResponseWrapper(localName = "dealPassCreditResponse", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.DealPassCreditResponse")
    @WebResult(name = "response", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
    public com.custsystems.integration.abs.DealPassCreditResponse dealPassCredit(
        @WebParam(name = "request", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
        com.custsystems.integration.abs.DealPassCreditRequest request
    ) throws DealPassCreditFaultMsg;

    /**
     * получение операций по счетам (UL, FL) по идентификаторам в АБС
     */
    @WebMethod
    @RequestWrapper(localName = "lastOperationInfo", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.LastOperationInfo")
    @ResponseWrapper(localName = "lastOperationInfoResponse", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.LastOperationInfoResponse")
    @WebResult(name = "response", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
    public com.custsystems.integration.abs.LastOperationInfoResponse lastOperationInfo(
        @WebParam(name = "request", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
        com.custsystems.integration.abs.LastOperationInfoBO request
    ) throws LastOperationInfoFaultMsg;

    /**
     * получение статуса исполнения документа (UL, FL)
     */
    @WebMethod
    @RequestWrapper(localName = "check", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.Check")
    @ResponseWrapper(localName = "checkResponse", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.CheckResponse")
    @WebResult(name = "response", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
    public com.custsystems.integration.abs.CheckResponse check(
        @WebParam(name = "request", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
        com.custsystems.integration.abs.CheckBO request
    ) throws CheckFaultMsg;

    /**
     * рублевое платежное поручение (UL)
     */
    @WebMethod
    @RequestWrapper(localName = "platpor", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.Platpor")
    @ResponseWrapper(localName = "platporResponse", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.PlatporResponse")
    @WebResult(name = "response", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
    public com.custsystems.integration.abs.PlatporResponse platpor(
        @WebParam(name = "request", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
        com.custsystems.integration.abs.PlatporBO request
    ) throws PlatporFaultMsg;

    /**
     * получение последних операций по счетам (UL, FL)
     */
    @WebMethod
    @RequestWrapper(localName = "lastOperation", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.LastOperation")
    @ResponseWrapper(localName = "lastOperationResponse", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.LastOperationResponse")
    @WebResult(name = "response", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
    public com.custsystems.integration.abs.LastOperationResponse lastOperation(
        @WebParam(name = "request", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
        com.custsystems.integration.abs.LastOperationBO request
    ) throws LastOperationFaultMsg;

    /**
     * паспорт сделки по контракту (UL)
     */
    @WebMethod
    @RequestWrapper(localName = "dealPassContract", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.DealPassContract")
    @ResponseWrapper(localName = "dealPassContractResponse", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.DealPassContractResponse")
    @WebResult(name = "response", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
    public com.custsystems.integration.abs.DealPassContractResponse dealPassContract(
        @WebParam(name = "request", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
        com.custsystems.integration.abs.DealPassContractRequest request
    ) throws DealPassContractFaultMsg;

    /**
     * получение списка вкладов клиента (UL, FL)
     */
    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "depositResponse", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", partName = "depositListResult")
    public DepositResponse depositList(
        @WebParam(partName = "depositListParameters", name = "deposit", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
        Deposit depositListParameters
    ) throws DepositListFaultMsg;

    /**
     * заявление на открытие вклада (FL)
     */
    @WebMethod
    @RequestWrapper(localName = "openDeposit", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.OpenDeposit")
    @ResponseWrapper(localName = "openDepositResponse", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.OpenDepositResponse")
    @WebResult(name = "response", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
    public com.custsystems.integration.abs.OpenDepositResponse openDeposit(
        @WebParam(name = "request", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
        com.custsystems.integration.abs.OpenDepositBO request
    ) throws OpenDepositFaultMsg;

    /**
     * получение курсов валют безналичного обмена (UL, FL)
     */
    //@ResponseWrapper(localName = "ccratesResponse", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.CcratesResponse")
    //public com.custsystems.integration.abs.CCRatesResponse ccrates(

    @WebMethod
    @RequestWrapper(localName = "ccrates", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.Ccrates")
    @ResponseWrapper(localName = "ccratesResponse", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.CcratesResponseMod")
    @WebResult(name = "response", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
    public com.custsystems.integration.abs.CCRatesResponseMod ccrates(
        @WebParam(name = "request", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
        com.custsystems.integration.abs.CCRatesBO request
    ) throws CcratesFaultMsg;

    /**
     * получение графика погашения кредита (UL, FL).
     */
    @WebMethod
    @RequestWrapper(localName = "paymentSchedule", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.PaymentSchedule")
    @ResponseWrapper(localName = "paymentScheduleResponse", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.PaymentScheduleResponse")
    @WebResult(name = "response", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
    public com.custsystems.integration.abs.PaymentScheduleResponse paymentSchedule(
        @WebParam(name = "request", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
        com.custsystems.integration.abs.PaymentScheduleRequest request
    ) throws PaymentScheduleFaultMsg;

    /**
     * справка о валютных операциях (UL)
     */
    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "inqCurrResponse", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", partName = "inqCurrResult")
    public InqCurrResponse inqCurr(
        @WebParam(partName = "inqCurrParameters", name = "inqCurrRequest", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
        InqCurrRequest inqCurrParameters
    ) throws InqCurrFaultMsg;

    /**
     * получение графика погашения кредита (UL, FL).
     */
    @WebMethod
    @RequestWrapper(localName = "mails2ClientList", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.Mails2ClientList")
    @ResponseWrapper(localName = "mails2ClientListResponse", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.Mails2ClientListResponse")
    @WebResult(name = "response", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
    public com.custsystems.integration.abs.Mails2ClientListResponse mails2ClientList() throws Mails2ClientListFaultMsg;

    /**
     * перевод между счетами /картами / депозитами клиента без конверсии (FL)
     */
    @WebMethod
    @RequestWrapper(localName = "accacc", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.Accacc")
    @ResponseWrapper(localName = "accaccResponse", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.AccaccResponse")
    @WebResult(name = "response", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
    public com.custsystems.integration.abs.AccAccResponse accacc(
        @WebParam(name = "request", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
        com.custsystems.integration.abs.AccAccBO request
    ) throws AccaccFaultMsg;

    /**
     * отзыв ранее выгруженного документа (UL, FL)
     */
    @WebMethod
    @RequestWrapper(localName = "cancel", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.Cancel")
    @ResponseWrapper(localName = "cancelResponse", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.CancelResponse")
    @WebResult(name = "response", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
    public com.custsystems.integration.abs.CancelResponse cancel(
        @WebParam(name = "request", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
        com.custsystems.integration.abs.CancelBO request
    ) throws CancelFaultMsg;

    /**
     * Получение информаци о сотруднике ЮЛ
     */
    @WebMethod
    @RequestWrapper(localName = "clientEmployeeInfo", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.ClientEmployeeInfo")
    @ResponseWrapper(localName = "custResponse", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.CustResponse")
    @WebResult(name = "response", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
    public com.custsystems.integration.abs.CustResponse clientEmployeeInfo(
        @WebParam(name = "request", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
        com.custsystems.integration.abs.CustBO request
    ) throws CustFaultMsg;

    /**
     * Платежное требование исходящее (UL)
     */
    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "paymentRequestOutgoingResponse", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", partName = "paymentRequestOutgoingwResult")
    public PaymentRequestOutgoingResponse paymentRequestOutgoing(
        @WebParam(partName = "paymentRequestOutgoingParameters", name = "paymentRequestOutgoingRequest", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
        PaymentRequestOutgoingRequest paymentRequestOutgoingParameters
    ) throws PaymentRequestOutgoingFaultMsg;

    /**
     * заявления о закрытии паспорта сделки (UL)
     */
    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "dealpassCloseResponse", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", partName = "dealpassCloseResult")
    public DealpassCloseResponse dealpassClose(
        @WebParam(partName = "dealpassCloseParameters", name = "dealpassCloseRequest", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
        DealpassCloseRequest dealpassCloseParameters
    ) throws DealpassCloseFaultMsg;

    /**
     * Получение информации по номеру счета (кастомизация хлынова)
     */
    @WebMethod
    @RequestWrapper(localName = "accInfo", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.AccInfo")
    @ResponseWrapper(localName = "accInfoResponse", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.AccInfoResponse")
    @WebResult(name = "response", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
    public com.custsystems.integration.abs.AccInfoRequestResponse accInfo(
        @WebParam(name = "request", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
        com.custsystems.integration.abs.AccInfoRequest request
    ) throws AccInfoFaultMsg;

    /**
     * переоформление паспорта сделки (UL)
     */
    @WebMethod
    @RequestWrapper(localName = "dealPassRenew", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.DealPassRenew")
    @ResponseWrapper(localName = "dealPassRenewResponse", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.DealPassRenewResponse")
    @WebResult(name = "response", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
    public com.custsystems.integration.abs.DealPassRenewResponse dealPassRenew(
        @WebParam(name = "request", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
        com.custsystems.integration.abs.DealPassRenewRequest request
    ) throws DealPassRenewFaultMsg;

    /**
     * получение клиента владельца счета (FL)
     */
    @WebMethod
    @RequestWrapper(localName = "accCust", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.AccCust")
    @ResponseWrapper(localName = "accCustResponse", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", className = "com.custsystems.integration.abs.absinterface.AccCustResponse")
    @WebResult(name = "response", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
    public com.custsystems.integration.abs.AccCustResponse accCust(
        @WebParam(name = "request", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
        com.custsystems.integration.abs.AccCustBO request
    ) throws AccCustFaultMsg;

    /**
     * справка о подтверждающих документах (UL)
     */
    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "inqConfResponse", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface", partName = "inqConfResult")
    public InqConfResponse inqConf(
        @WebParam(partName = "inqConfParameters", name = "inqConfRequest", targetNamespace = "http://custsystems.com/integration/abs/ABSInterface")
        InqConfRequest inqConfParameters
    ) throws InqConfFaultMsg;

	DepositResponse deposit(DepositBO request) throws DepositFaultMsg;
}
