
package ru.unitarius.integration.service.loans;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.4.redhat-1
 * 2016-12-20T12:11:33.407+03:00
 * Generated source version: 3.1.4.redhat-1
 */

@WebFault(name = "Fault", targetNamespace = "http://unitarius.ru/integration/schema/common")
public class MsgFault extends Exception {
    
    private ru.unitarius.integration.schema.common.FaultType fault;

    public MsgFault() {
        super();
    }
    
    public MsgFault(String message) {
        super(message);
    }
    
    public MsgFault(String message, Throwable cause) {
        super(message, cause);
    }

    public MsgFault(String message, ru.unitarius.integration.schema.common.FaultType fault) {
        super(message);
        this.fault = fault;
    }

    public MsgFault(String message, ru.unitarius.integration.schema.common.FaultType fault, Throwable cause) {
        super(message, cause);
        this.fault = fault;
    }

    public ru.unitarius.integration.schema.common.FaultType getFaultInfo() {
        return this.fault;
    }
}
