package ru.unitarius.integration.service.loans;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.4.redhat-1
 * 2016-12-20T12:11:33.447+03:00
 * Generated source version: 3.1.4.redhat-1
 * 
 */
@WebService(targetNamespace = "http://unitarius.ru/integration/service/loans", name = "PortTypeLoansService")
@XmlSeeAlso({ru.unitarius.integration.schema.common.ObjectFactory.class, ru.unitarius.integration.schema.loans.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PortTypeLoansService {

    @WebMethod(action = "http://unitarius.ru/integration/service/loans/getLoansList")
    @WebResult(name = "LoansFindListRes", targetNamespace = "http://unitarius.ru/integration/schema/loans", partName = "parameters")
    public ru.unitarius.integration.schema.loans.LoansFindListResType getLoansList(
        @WebParam(partName = "parameters", name = "LoanFindListReq", targetNamespace = "http://unitarius.ru/integration/schema/loans")
        ru.unitarius.integration.schema.loans.LoanFindListReqType parameters
    ) throws MsgFault;

    @WebMethod(action = "http://unitarius.ru/integration/service/loans/getPaymentSchedule")
    @WebResult(name = "PaymentScheduleRes", targetNamespace = "http://unitarius.ru/integration/schema/loans", partName = "parameters")
    public ru.unitarius.integration.schema.loans.PaymentScheduleResType getPaymentSchedule(
        @WebParam(partName = "parameters", name = "PaymentScheduleReq", targetNamespace = "http://unitarius.ru/integration/schema/loans")
        ru.unitarius.integration.schema.loans.PaymentScheduleReqType parameters
    ) throws MsgFault;

    @WebMethod(action = "http://unitarius.ru/integration/service/loans/getStatement")
    @WebResult(name = "StatementRes", targetNamespace = "http://unitarius.ru/integration/schema/loans", partName = "parameters")
    public ru.unitarius.integration.schema.loans.StatementResType getStatement(
        @WebParam(partName = "parameters", name = "StatementReq", targetNamespace = "http://unitarius.ru/integration/schema/loans")
        ru.unitarius.integration.schema.loans.StatementReqType parameters
    ) throws MsgFault;

    @WebMethod(action = "http://unitarius.ru/integration/service/loans/getLoan")
    @WebResult(name = "LoanRes", targetNamespace = "http://unitarius.ru/integration/schema/loans", partName = "parameters")
    public ru.unitarius.integration.schema.loans.LoanType getLoan(
        @WebParam(partName = "parameters", name = "LoanFindByIDReq", targetNamespace = "http://unitarius.ru/integration/schema/loans")
        ru.unitarius.integration.schema.loans.LoanFindByIDReqType parameters
    ) throws MsgFault;
}
