package lv.d8.cortexws.card.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4.redhat-1
 * 2017-07-04T10:25:43.860+03:00
 * Generated source version: 3.1.4.redhat-1
 * 
 */
@WebService(targetNamespace = "http://service.card.cortexws.d8.lv", name = "CardPortType")
@XmlSeeAlso({ObjectFactory.class, lv.d8.cortexws.card.valueobj.xsd.ObjectFactory.class, lv.d8.cortexws.common.valueobj.xsd.ObjectFactory.class, lv.d8.ws.valueobj.xsd.ObjectFactory.class})
public interface CardPortType {

    @WebMethod(action = "urn:getBalance")
    @Action(input = "urn:getBalance", output = "urn:getBalanceResponse")
    @RequestWrapper(localName = "getBalance", targetNamespace = "http://service.card.cortexws.d8.lv", className = "lv.d8.cortexws.card.service.GetBalance")
    @ResponseWrapper(localName = "getBalanceResponse", targetNamespace = "http://service.card.cortexws.d8.lv", className = "lv.d8.cortexws.card.service.GetBalanceResponse")
    @WebResult(name = "return", targetNamespace = "http://service.card.cortexws.d8.lv")
    public lv.d8.cortexws.card.valueobj.xsd.GetBalanceRspsInfo getBalance(
        @WebParam(name = "param0", targetNamespace = "http://service.card.cortexws.d8.lv")
        lv.d8.cortexws.card.valueobj.xsd.GetBalanceRqstInfo param0
    );

    @WebMethod(action = "urn:newStatus")
    @Action(input = "urn:newStatus", output = "urn:newStatusResponse")
    @RequestWrapper(localName = "newStatus", targetNamespace = "http://service.card.cortexws.d8.lv", className = "lv.d8.cortexws.card.service.NewStatus")
    @ResponseWrapper(localName = "newStatusResponse", targetNamespace = "http://service.card.cortexws.d8.lv", className = "lv.d8.cortexws.card.service.NewStatusResponse")
    @WebResult(name = "return", targetNamespace = "http://service.card.cortexws.d8.lv")
    public lv.d8.cortexws.card.valueobj.xsd.NewStatusRspsInfo newStatus(
        @WebParam(name = "param0", targetNamespace = "http://service.card.cortexws.d8.lv")
        lv.d8.cortexws.card.valueobj.xsd.NewStatusRqstInfo param0
    );

    @WebMethod(action = "urn:getStatus")
    @Action(input = "urn:getStatus", output = "urn:getStatusResponse")
    @RequestWrapper(localName = "getStatus", targetNamespace = "http://service.card.cortexws.d8.lv", className = "lv.d8.cortexws.card.service.GetStatus")
    @ResponseWrapper(localName = "getStatusResponse", targetNamespace = "http://service.card.cortexws.d8.lv", className = "lv.d8.cortexws.card.service.GetStatusResponse")
    @WebResult(name = "return", targetNamespace = "http://service.card.cortexws.d8.lv")
    public lv.d8.cortexws.card.valueobj.xsd.GetStatusRspsInfo getStatus(
        @WebParam(name = "param0", targetNamespace = "http://service.card.cortexws.d8.lv")
        lv.d8.cortexws.card.valueobj.xsd.GetStatusRqstInfo param0
    );
}
